baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Filip Livancic - Portfolio'
theme = "hugo-PaperMod"

[params.profileMode]
enabled = true
title = "<Title>" # optional default will be site title
subtitle = "This is subtitle"
imageUrl = "<image link>" # optional
imageTitle = "<title of image as alt>" # optional
imageWidth = 120 # custom size
imageHeight = 120 # custom size


[[params.socialIcons]] # optional
name = "github"
url = "https://github.com/filpill"

[[params.socialIcons]] # optional
name = "linkedin"
url = "https://www.linkedin.com/in/filip-livancic"
