#!/bin/bash

echo "Deploying Website Updates to Github Pages"
cd ..

# Build project
hugo -t hugo-PaperMod

# Commit and Push Changes
cd $HOME/projects/blog-web/public
git add .
msg="rebuilding site `date`"
git commit -m "$msg"
git push origin main
cd ..
