#!/bin/sh
directory="$HOME/projects/blog-web/content/files"
file="filip-livancic-cv.pdf"
url="https://raw.githubusercontent.com/Filpill/LaTeX-CV/main/cv/filip-livancic-cv.pdf"
wget $url -O $directory/$file
